version: '3.9'

services:
  frontend:
    container_name: leading_basic_c_app
    build:
      context: ./app  # ReactアプリケーションのDockerfileが存在するディレクトリへのパス
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000  # Reactアプリケーションのポート番号をホストのポート番号にマッピング
    volumes:
      - ./app:/app  # Reactアプリケーションのソースコードをコンテナにマウント
      - node_modules:/app/node_modules
    depends_on:
      - api  # Djangoサービスに依存する

  api:
    container_name: leading_basic_c_api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/code
    env_file:
      - backend/.env
    command: [
      "bash",
      "-c",
      "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ]
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: leading_basic_c_db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 12m
        max-file: '3'

volumes:
  postgres_data:
  node_modules: