openapi: 3.0.3

info:
  title: TwitterClone_C API
  version: 1.0.0
  description: TwitterClone_C OpenAPI Schema

servers:
  - url: http://localhost:8000/api/v1
    description: Local server (uses local data)


paths:
  /auth/users:
    post:
      operationId: TempUserCreation
      summary: 仮登録
      description: 仮登録
      tags:
        - auth
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 名前
                  example: example_user
                email:
                  type: string
                  description: メールアドレス
                  example: example@example.com
                password:
                  type: string
                  description: パスワード
                  example: gauoyr3ew
                re_password:
                  type: string
                  description: パスワード確認用
                  example: gauoyr3ew

      responses:
        200:
          description: 仮登録完了
          content: 
            application/json:
              schema:
                type: object
                description: ユーザー
                properties:
                  id:
                    type: string
                    format: uuid
                    description: ユーザーID
                  username:
                    type: string
                    description: ユーザー名
                  email:
                    type: string
                    format: email
                    description: メールアドレス
                  
        400:
          description: 仮登録失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          description: エラーコード
                        detail:
                          type: string
                          description: エラー詳細

              examples:
                名前未入力:
                  value:
                    errors:
                      - code: "001"
                        detail: 名前を入力してください
                名前上限文字数:
                  value:
                    errors:
                      - code: "002"
                        detail: 名前は255文字まで入力可能です
                メールアドレス未入力:
                  value:
                    errors:
                      - code: "003"
                        detail: メールアドレスを入力してください
                メールアドレス上限文字数:
                  value:
                    errors:
                      - code: "004"
                        detail: メールアドレスは255文字まで入力可能です
                重複メールアドレス:
                  value:
                    errors:
                      - code: "005"
                        detail: 既に登録されたメールアドレスです
                重複ユーザー名:
                  value:
                    errors:
                      - code: "006"
                        detail: 既に登録されたユーザー名です
                単純すぎるパスワード:
                  value:
                    errors:
                      - code: "007"
                        detail: 簡単すぎます

  /auth/users/activation:
    post:
      operationId: UserCreation
      summary: 本登録
      description: 本仮登録
      tags:
        - auth
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                  description: ユーザーID
                  example: Mn
                token:
                  type: string
                  description: 本登録token
                  example: faefasgist134uaosgh

      responses:
        201:
          description: 本登録完了
          content: 
            application/json:
              schema:
                type: object
                description: ユーザー
                properties:
                  redirect_url:
                    type: string
                    description: リダイレクト先のURL(わからないのでとりあえず)
                    example: http://localhost:8000/api/v1/~~/


